import React,{useEffect,useMemo,useState} from 'react';

const groups={
  '12-week sprint':['Week 1 — Baseline and SOC foundations','Week 2 — Networking and Windows telemetry','Week 3 — Wazuh operations','Week 4 — Event 4625 investigation','Week 5 — Detection engineering','Week 6 — Incident response','Week 7 — Git and GitHub workflow','Week 8 — Cloud-security fundamentals','Week 9 — Threat intelligence and ATT&CK','Week 10 — Automation basics','Week 11 — Communication and interview evidence','Week 12 — Capstone review'],
  'Labs':['Windows event-log investigation','Wazuh rule and alert triage','Network traffic analysis','Brute-force investigation','Phishing/IOC triage tabletop','Cloud-security control mapping','GitHub evidence workflow','Mini SOC case management'],
  'Portfolio':['SOC Analyst Portfolio index','Event 4625 Investigation Pack','Wazuh Detection Pack','Incident Response Runbook','Cloud Security Baseline','SOC Capstone Case Study'],
  'Professional growth':['Communication practice','Mentor review #1','Mentor review #2','Mentor review #3','CV/LinkedIn evidence refresh','Mock SOC interview']
};
const key='nm-idr-progress-v1';
export default function ProgressWorkspace(){const [state,setState]=useState({});useEffect(()=>{try{setState(JSON.parse(localStorage.getItem(key)||'{}'))}catch{}},[]);useEffect(()=>{localStorage.setItem(key,JSON.stringify(state))},[state]);const all=useMemo(()=>Object.values(groups).flat(),[]);const done=all.filter(x=>state[x]).length;const pct=Math.round((done/all.length)*100);const toggle=(x)=>setState(s=>({...s,[x]:!s[x]}));const exportData=()=>{const blob=new Blob([JSON.stringify({learner:'Nkateko Mtembi',exportedAt:new Date().toISOString(),progress:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nkateko-idr-progress.json';a.click();URL.revokeObjectURL(a.href)};return <div className="progress-shell"><div className="progress-summary"><div className="progress-stat"><span>Overall progress</span><strong>{pct}%</strong></div><div className="progress-stat"><span>Completed items</span><strong>{done}/{all.length}</strong></div><div className="progress-stat"><span>Sprint weeks</span><strong>{groups['12-week sprint'].filter(x=>state[x]).length}/12</strong></div><div className="progress-stat"><span>Portfolio items</span><strong>{groups['Portfolio'].filter(x=>state[x]).length}/6</strong></div></div><div className="progress-grid">{Object.entries(groups).map(([name,items])=><section className="progress-card" key={name}><h3>{name}</h3>{items.map(item=><label className="progress-item" key={item}><input type="checkbox" checked={Boolean(state[item])} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</section>)}</div><div className="progress-actions"><button className="button button--primary" onClick={exportData}>Export progress JSON</button><button className="button button--secondary" onClick={()=>window.print()}>Print / Save PDF</button><button className="button button--secondary" onClick={()=>{if(window.confirm('Reset all IDR progress?'))setState({})}}>Reset progress</button></div></div>}
