import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
const root=process.cwd(), outDir=path.join(root,'static','downloads');fs.mkdirSync(outDir,{recursive:true});const output=path.join(outDir,'Nkateko_Mtembi_Individual_Development_Roadmap.pdf');
const docs=[['Executive Summary','docs/overview.md'],['Capability Profile','docs/profile.md'],['Career Pathway','docs/pathway.md'],['12-Month Roadmap','docs/roadmap.md'],['12-Week Applied Sprint','docs/12-week-sprint.md'],['Credentials','docs/credentials.md'],['Curriculum','docs/curriculum.md'],['Hands-On Labs','docs/labs.md'],['Assignments','docs/assignments.md'],['Portfolio Projects','docs/projects.md'],['Calendar','docs/calendar.md'],['Goals and KPIs','docs/kpis.md'],['Mentor Reviews','docs/mentor.md'],['Governance','docs/governance.md'],['Resources','docs/resources.md'],['References','docs/references.md'],['Download and Sign-Off','docs/download-and-review.md']];
const doc=new PDFDocument({size:'A4',margins:{top:52,right:46,bottom:52,left:46},info:{Title:'Nkateko Mtembi Individual Development Roadmap',Author:'Skunkworks Academy'}});const stream=fs.createWriteStream(output);doc.pipe(stream);const width=()=>doc.page.width-92,bottom=()=>doc.page.height-58;
function footer(){doc.save().font('Helvetica').fontSize(7).fillColor('#667085').text('Skunkworks Academy · Nkateko Mtembi IDR · Public evidence must be sanitised.',46,doc.page.height-32,{width:430,lineBreak:false});doc.text(`Page ${doc.page.number}`,500,doc.page.height-32,{width:45,align:'right',lineBreak:false}).restore()}
function page(label){doc.addPage();doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#0F62FE').text('SKUNKWORKS ACADEMY',46,27,{lineBreak:false});doc.font('Helvetica').fillColor('#667085').text(label.toUpperCase(),300,27,{width:245,align:'right',lineBreak:false});doc.strokeColor('#D0D5DD').moveTo(46,42).lineTo(549,42).stroke();doc.x=46;doc.y=57;footer()}
function ensure(h=30,label='IDR'){if(doc.y+h>bottom())page(label)}
function clean(s){return s.replace(/<[^>]+>/g,' ').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1 — $2').replace(/`([^`]+)`/g,'$1').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/\*([^*]+)\*/g,'$1').replace(/\s+/g,' ').trim()}
function body(t,label){if(!t)return;ensure(28,label);doc.font('Helvetica').fontSize(9).fillColor('#161616').text(t,{lineGap:2.2});doc.moveDown(.18)}
function render(file,label){const raw=fs.readFileSync(path.join(root,file),'utf8').replace(/^---[\s\S]*?---\s*/,'');let fence=false;for(const row of raw.split(/\r?\n/)){let line=row.trim();if(line.startsWith('```')){fence=!fence;continue}if(fence){if(line){ensure(18,label);doc.font('Courier').fontSize(7.4).fillColor('#344054').text(line,{width:width()})}continue}if(!line||line.startsWith('<div')||line.startsWith('</div')||line.startsWith(':::'))continue;if(/^#\s+/.test(line)){ensure(40,label);doc.font('Helvetica-Bold').fontSize(19).fillColor('#101828').text(clean(line.replace(/^#\s+/,'')));doc.moveDown(.3);continue}if(/^##\s+/.test(line)){ensure(32,label);doc.font('Helvetica-Bold').fontSize(12.5).fillColor('#101828').text(clean(line.replace(/^##\s+/,'')));doc.moveDown(.18);continue}if(/^###\s+/.test(line)){ensure(26,label);doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#101828').text(clean(line.replace(/^###\s+/,'')));doc.moveDown(.12);continue}if(/^[-*]\s+/.test(line)){ensure(24,label);const text=clean(line.replace(/^[-*]\s+/,''));const y=doc.y;doc.font('Helvetica-Bold').fontSize(9).fillColor('#0F62FE').text('•',46,y,{width:14,lineBreak:false});doc.font('Helvetica').fontSize(9).fillColor('#161616').text(text,62,y,{width:width()-16,lineGap:2});doc.x=46;doc.moveDown(.12);continue}if(line.startsWith('|')){body(clean(line.replace(/^\||\|$/g,'').replace(/\|/g,' · ')),label);continue}if(line.startsWith('>')){body(clean(line.replace(/^>\s*/,'')),label);continue}body(clean(line),label)}}
doc.rect(0,0,doc.page.width,10).fill('#0F62FE');doc.font('Helvetica-Bold').fontSize(9).fillColor('#0F62FE').text('SKUNKWORKS ACADEMY',46,92);doc.font('Helvetica-Bold').fontSize(28).fillColor('#101828').text('Individual Development Roadmap',46,122,{width:width()});doc.font('Helvetica-Bold').fontSize(30).fillColor('#101828').text('Nkateko Mtembi',46,165,{width:width()});doc.font('Helvetica').fontSize(12).fillColor('#667085').text('SOC Operations · Wazuh SIEM · Threat Detection · Incident Response · Cloud Security',46,215,{width:width(),lineGap:3});doc.y=285;doc.save().roundedRect(46,doc.y,width(),118,8).fill('#EEF4FF').restore();doc.font('Helvetica-Bold').fontSize(11).fillColor('#101828').text('Recommended development placement',60,302);doc.font('Helvetica').fontSize(9.5).fillColor('#101828').text('Primary: Junior SOC Analyst → SOC Analyst / Security Operations Analyst\nSecondary growth: Detection Engineering / Cloud Security\nLearning mode: self-paced, hands-on and evidence based\nInitial execution: 12-week applied sprint\nLong-term direction: security operations leadership and subject-matter growth',60,327,{width:width()-28,lineGap:4});footer();
for(const [label,file] of docs){page(label);render(file,label)}doc.end();await new Promise((resolve,reject)=>{stream.on('finish',resolve);stream.on('error',reject)});const bytes=fs.readFileSync(output);if(bytes.subarray(0,5).toString('ascii')!=='%PDF-')throw new Error('Invalid generated PDF');if(bytes.length<25000)throw new Error(`Generated PDF unexpectedly small: ${bytes.length}`);console.log(`Generated ${path.relative(root,output)} (${bytes.length} bytes).`);
